### ISSUE TITLE
jsstyle should set file encoding to UTF-8

### ISSUE THREAD

**Issue by melloc** [davepacheco/jsstyle#20]
When `jsstyle` parses a file, it assumes that it's ASCII. This means that when it checks the length of a line, it ends up checking the number of bytes, instead of the number of characters. A better default would be to assume the file is UTF-8. @trentm suggested the following change:

``` diff
diff --git a/jsstyle b/jsstyle
index 9df33c9..4b3eaca 100755
--- a/jsstyle
+++ b/jsstyle
@@ -210,6 +210,7 @@ my $err_stat = 0;           # exit status
 if ($#ARGV >= 0) {
        foreach my $arg (@ARGV) {
                my $fh = new IO::File $arg, "r";
+               binmode($fh, ":encoding(UTF-8)");
                if (!defined($fh)) {
                        printf "%s: cannot open\n", $arg;
                } else {
```

I don't know if this should be more configurable, or if always assuming UTF-8 is a fine default for now.

**Comment by trentm** [comment]
some notes from: http://www.perl.com/pub/2012/05/perlunicook-specify-a-files-encoding.html

I'm not sure if there is a reason to prefer one or the other of:

1. `open(my $fh, '<:encoding(UTF-8)', $filename)`
2. `new IO::File`   +   `binmode`

However the above worked, so...


Another concern could *conceivably* be other 8-bit encodings for source files. But frankly I'd be inclined to bias to UTF-8 and non-ascii that doesn't use UTF-8 can suffer. This is just a checker after all, so shouldn't have run/build impact.

**Comment by davepacheco** [comment]
How did this come up?

I would assume UTF-8 is fine for the foreseeable future.

**Comment by melloc** [comment]
I was writing some tests for checking input that contained Unicode characters, and found that `jsstyle` thought that a line was 86 characters, when it was actually 74. I could wrap the line earlier, but if having `jsstyle` interpret its input as UTF-8 is okay, then that seems like a cleaner solution.

**Comment by trentm** [comment]
The example from mib discussion:

```
[20:57:43] <Cody Mello> perl -e 'print length($ARGV[0]), "\n";' ' 'FROM tag "☃" = "ﺮﺠﻟ ﺎﻠﺜﻠﺟ" TO tag "⛄" ALLOW tcp PORT 22'
[20:57:50] <Cody Mello> That prints 75.
```

**Comment by davepacheco** [comment]
This was integrated.
